### ISSUE TITLE
Add service testing with docker and travis

### ISSUE THREAD

**Issue by hexfusion** [devcamps/camps#34]
We need some decent tests against different versions of services such as mysql, postgres, apache etc. Setting up travis to run these tests with docker is going to be the easiest way I can see.

https://docs.travis-ci.com/user/docker/

re: https://github.com/devcamps/camps/pull/33

**Comment by hexfusion** [comment]
After thinking about this the test will have a series of simple camp_types. These will use a variation of services combinations. For now, I am going to keep it simple and test apache-2.4 with mysql 5.x.  Compose will fire up all of the services together and we can just call them by there names ie mysql_5.1 so it should be pretty simple to manage dsn's etc just run each on a diffent port.

```
version: '2' 
services:

    mysql_5.1:
        image:  mysql/mysql-server:5.1
        restart: always
        ports:
            - 3306
    mysql_5.6:
        image:  mysql/mysql-server:5.6
        restart: always
        ports:
            - 3307
    mysql_5.7:
        image:  mysql/mysql-server:5.7
        restart: always
        ports:
            - 3308
etc..
```
